import { FormEvent, useEffect, useState } from 'react'
import { Activity, ArchiveRestore, CheckCircle2, Database, Download, FileClock, Gauge, KeyRound, Plus, RefreshCw, Search, Server, ShieldCheck, UserPlus, UsersRound, X } from 'lucide-react'
import { postJson, requestJson } from '../api'
import { getSession } from '../auth'
import MfaPanel from './MfaPanel'
import LlmSettingsPanel from './LlmSettingsPanel'

type Tab='overview'|'logs'|'backup'|'users'|'models'|'security'
interface Overview{data_records:number;transfer_success_rate:number;active_alerts:number;active_users:number;passengers:number;received_packages:number;rule_executions_24h:number;transfer_bytes:number;user_operations_24h:number;api_requests_24h:number;api_errors_24h:number;avg_response_ms:number;p95_response_ms:number;window_hours:number;generated_at:string}
interface Audit{ id:string;type:string;level:string;user:string;role:string;ip:string;action:string;resource:string;detail:string;result:string;request_id:string;timestamp:string }
interface Backup{backup_id:string;type:string;status:string;size:number;checksum:string|null;created_at:string;retention_until:string|null}
interface User{user_id:string;username:string;display_name:string;role:string;status:string;auth_source:'local'|'ldap';failed_attempts:number;mfa_enabled:boolean;locked_until:string|null;last_login:string|null;created_at:string}
const roleLabel:Record<string,string>={system_admin:'系统管理员',data_analyst:'数据分析员',port_operator:'口岸操作员',auditor:'审计员',read_only:'只读用户'}
const bytes=(value:number)=>value<1024?'0 B':value<1024**2?`${(value/1024).toFixed(1)} KB`:value<1024**3?`${(value/1024**2).toFixed(1)} MB`:`${(value/1024**3).toFixed(1)} GB`

export default function AdminPage({connected:_connected}:{connected:boolean}){
 const isAuditor=getSession()?.user.role==='auditor';const[tab,setTab]=useState<Tab>(()=>isAuditor?'logs':'overview');const[overview,setOverview]=useState<Overview|null>(null);const[logs,setLogs]=useState<Audit[]>([]);const[backups,setBackups]=useState<Backup[]>([]);const[users,setUsers]=useState<User[]>([]);const[busy,setBusy]=useState(false);const[toast,setToast]=useState('');const[modal,setModal]=useState(false);const[form,setForm]=useState({username:'',display_name:'',password:'',role:'read_only'});const[statsHours,setStatsHours]=useState(24);const[logType,setLogType]=useState('');const[logActor,setLogActor]=useState('');const[logStart,setLogStart]=useState('')
 const notify=(value:string)=>{setToast(value);setTimeout(()=>setToast(''),3000)}
 useEffect(()=>{if(!isAuditor)requestJson<{mfa_enabled:boolean}>('/auth/me').then(me=>{if(!me.mfa_enabled)setTab('security')}).catch(()=>undefined)},[isAuditor])
 const load=async()=>{setBusy(true);try{if(tab==='overview')setOverview(await requestJson(`/admin/stats/overview?hours=${statsHours}`));if(tab==='logs'){const query=new URLSearchParams({page_size:'200'});if(logType)query.set('type',logType);if(logActor)query.set('actor',logActor);if(logStart)query.set('start',new Date(logStart).toISOString());const result=await requestJson<{items:Audit[]}>(`/admin/logs?${query}`);setLogs(result.items)}if(tab==='backup')setBackups(await requestJson('/admin/backups'));if(tab==='users')setUsers(await requestJson('/admin/users'))}catch(error){notify(error instanceof Error?error.message:'管理数据加载失败')}finally{setBusy(false)}}
 useEffect(()=>{load()},[tab,statsHours])
 const createBackup=async()=>{setBusy(true);try{const item=await postJson<Backup>('/admin/backups',{backup_type:'full'});setBackups(current=>[item,...current]);notify('全量备份已完成并通过校验')}catch(error){notify(error instanceof Error?error.message:'备份失败')}finally{setBusy(false)}}
 const restore=async(item:Backup)=>{const confirmation=window.prompt(`恢复将覆盖当前数据库并先创建快照。请输入备份编号确认：\n${item.backup_id}`);if(confirmation!==item.backup_id)return;setBusy(true);try{await postJson(`/admin/backups/${item.backup_id}/restore`,{confirmation});notify('恢复完成，请重新登录验证数据')}catch(error){notify(error instanceof Error?error.message:'恢复失败')}finally{setBusy(false)}}
 const createUser=async(event:FormEvent)=>{event.preventDefault();setBusy(true);try{const item=await postJson<User>('/admin/users',form);setUsers(current=>[...current,item]);setModal(false);setForm({username:'',display_name:'',password:'',role:'read_only'});notify('用户已创建')}catch(error){notify(error instanceof Error?error.message:'用户创建失败')}finally{setBusy(false)}}
 const updateUser=async(user:User,values:Record<string,string>)=>{setBusy(true);try{const item=await requestJson<User>(`/admin/users/${user.user_id}`,{method:'PATCH',body:JSON.stringify(values)});setUsers(current=>current.map(value=>value.user_id===item.user_id?item:value));notify('用户权限已更新')}catch(error){notify(error instanceof Error?error.message:'用户更新失败')}finally{setBusy(false)}}
 const resetPassword=async(user:User)=>{const password=window.prompt(`为 ${user.username} 设置不少于10位的新密码`);if(!password)return;try{await postJson(`/admin/users/${user.user_id}/reset-password`,{password});notify('密码已重置，账号锁定状态已解除')}catch(error){notify(error instanceof Error?error.message:'密码重置失败')}}
 const resetMfa=async(user:User)=>{if(!window.confirm(`确认重置 ${user.username} 的双因素认证？该用户必须重新绑定后才能执行管理员敏感操作。`))return;try{await postJson(`/admin/users/${user.user_id}/reset-mfa`);setUsers(current=>current.map(item=>item.user_id===user.user_id?{...item,mfa_enabled:false}:item));notify('双因素认证已重置')}catch(error){notify(error instanceof Error?error.message:'双因素认证重置失败')}}
 const exportLogs=()=>{const csv=['时间,类型,用户,IP,操作,资源,结果',...logs.map(item=>[item.timestamp,item.type,item.user,item.ip,item.action,item.resource,item.result].map(value=>`"${String(value).replaceAll('"','""')}"`).join(','))].join('\n');const url=URL.createObjectURL(new Blob([`\ufeff${csv}`],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='审计日志.csv';a.click();URL.revokeObjectURL(url)}
 const exportOverview=()=>{if(!overview)return;const csv=['指标,值',...Object.entries(overview).map(([key,value])=>`"${key}","${value}"`)].join('\n');const url=URL.createObjectURL(new Blob([`\ufeff${csv}`],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`系统统计_${statsHours}h.csv`;a.click();URL.revokeObjectURL(url)}
 return <div className="business-page page-enter admin-page"><section className="page-heading compact-heading"><div><span className="eyebrow">SYSTEM ADMINISTRATION</span><h1>系统管理</h1><p>真实运行统计、不可删除审计日志、备份恢复、模型连接与角色权限管理。</p></div><div className="heading-actions"><div className="page-tabs">{!isAuditor&&<button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>运行总览</button>}{isAuditor&&<button className={tab==='logs'?'active':''} onClick={()=>setTab('logs')}>审计日志</button>}{!isAuditor&&<><button className={tab==='backup'?'active':''} onClick={()=>setTab('backup')}>备份恢复</button><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}>用户权限</button><button className={tab==='models'?'active':''} onClick={()=>setTab('models')}>大模型</button><button className={tab==='security'?'active':''} onClick={()=>setTab('security')}>双因素认证</button></>}</div><button className="icon-button" disabled={busy} onClick={load}><RefreshCw className={busy?'spin':''} size={17}/></button></div></section>
 {tab==='overview'&&<><div className="overview-toolbar"><span className="overview-toolbar__label">统计时段</span><div className="overview-range-buttons"><button className={statsHours===24?'active':''} onClick={()=>setStatsHours(24)}>近24小时</button><button className={statsHours===168?'active':''} onClick={()=>setStatsHours(168)}>近7天</button><button className={statsHours===720?'active':''} onClick={()=>setStatsHours(720)}>近30天</button></div><button className="secondary-button" onClick={exportOverview}><Download size={15}/>导出统计</button></div><section className="admin-kpis"><article><span className="round-icon cyan"><Database size={20}/></span><div><small>事件数据量</small><strong>{overview?.data_records??0}</strong><span>数据库实时统计</span></div></article><article><span className="round-icon blue"><Gauge size={20}/></span><div><small>摆渡成功率</small><strong>{overview?.transfer_success_rate??0}<em>%</em></strong><span>{bytes(overview?.transfer_bytes??0)} 已完成</span></div></article><article><span className="round-icon violet"><UsersRound size={20}/></span><div><small>有效用户</small><strong>{overview?.active_users??0}</strong><span>五类角色授权</span></div></article><article><span className="round-icon orange"><Activity size={20}/></span><div><small>API P95 响应</small><strong>{overview?.p95_response_ms??0}<em>ms</em></strong><span>24h {overview?.api_requests_24h??0} 次请求</span></div></article><article><span className="round-icon green"><Server size={20}/></span><div><small>接收数据包</small><strong>{overview?.received_packages??0}</strong><span>幂等入库记录</span></div></article></section><section className="admin-bottom-grid"><article className="panel service-grid"><header className="panel__header"><div><span className="panel__eyebrow">BUSINESS DATA</span><h2>业务数据概况</h2></div><CheckCircle2 size={18} className="text-teal"/></header><div>{[['生效预警',overview?.active_alerts??0,'风险中心'],['内网旅客',overview?.passengers??0,'加密存储'],['用户操作',overview?.user_operations_24h??0,'最近24小时'],['API错误',overview?.api_errors_24h??0,'最近24小时']].map(([name,value,note])=><div key={String(name)}><span className="service-ok"><CheckCircle2 size={14}/></span><span><b>{name}</b><small>{note}</small></span><em>{value}</em></div>)}</div></article><article className="panel security-summary"><header className="panel__header"><div><span className="panel__eyebrow">SECURITY</span><h2>安全控制</h2></div><ShieldCheck size={19} className="text-teal"/></header>{[['账号锁定','5次失败 / 15分钟'],['访问令牌','平台受众隔离'],['敏感数据','AES-256-GCM 字段加密'],['操作审计','不可提供删除接口']].map(([a,b])=><div className="security-row" key={a}><KeyRound size={14}/><span>{a}</span><b>{b}</b></div>)}</article></section></>}
 {tab==='logs'&&<section className="panel log-panel"><header className="panel__header"><div><span className="panel__eyebrow">AUDIT TRAIL</span><h2>操作与安全审计</h2></div><button className="secondary-button" onClick={exportLogs}><Download size={15}/>导出日志</button></header><div className="table-toolbar"><label className="table-search"><Search size={16}/><input value={logActor} onChange={event=>setLogActor(event.target.value)} placeholder="操作人"/></label><select value={logType} onChange={event=>setLogType(event.target.value)}><option value="">全部类型</option>{['operation','security','collection','transfer','integration'].map(item=><option key={item}>{item}</option>)}</select><input type="datetime-local" value={logStart} onChange={event=>setLogStart(event.target.value)}/><button className="secondary-button" onClick={load}><Search size={14}/>查询</button><span className="source-tag">日志无删除接口</span></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>时间</th><th>类型</th><th>操作人 / IP</th><th>操作</th><th>资源</th><th>结果</th></tr></thead><tbody>{logs.map(item=><tr key={item.id}><td>{new Date(item.timestamp).toLocaleString('zh-CN')}</td><td><span className={`log-type log-type--${item.type}`}>{item.type}</span></td><td><b>{item.user}</b><small className="block-small">{item.ip}</small></td><td>{item.action}</td><td>{item.resource}</td><td><span className={item.result==='success'?'result-ok':'result-fail'}>{item.result}</span></td></tr>)}</tbody></table></div></section>}
 {tab==='backup'&&<section className="backup-layout"><article className="panel backup-main"><header className="panel__header"><div><span className="panel__eyebrow">VERIFIED BACKUPS</span><h2>备份与恢复</h2></div><button className="primary-button" disabled={busy} onClick={createBackup}><Plus size={15}/>立即全量备份</button></header><div className="backup-policy"><span><ShieldCheck size={19}/></span><div><b>备份在服务端真实生成并执行 SHA-256 校验</b><p>恢复操作校验文件路径、完整性和确认码，并在覆盖前生成当前数据库快照。</p></div></div><div className="backup-list"><div className="backup-list__head"><span>备份编号</span><span>类型</span><span>状态</span><span>大小</span><span>校验和</span><span>保留至</span><span/></div>{backups.map(item=><div className="backup-row" key={item.backup_id}><span><FileClock size={17}/><b>{item.backup_id}</b><small>{new Date(item.created_at).toLocaleString('zh-CN')}</small></span><span className="source-tag">{item.type}</span><span className={item.status==='verified'?'result-ok':'result-fail'}>{item.status}</span><span>{bytes(item.size)}</span><code>{item.checksum?.slice(0,12)??'—'}</code><span>{item.retention_until??'—'}</span><span><button className="row-action" title="恢复" onClick={()=>restore(item)}><ArchiveRestore size={14}/></button></span></div>)}</div></article></section>}
 {tab==='users'&&<section className="panel table-panel"><header className="panel__header"><div><span className="panel__eyebrow">IDENTITY & ACCESS</span><h2>用户与角色</h2></div><button className="primary-button" onClick={()=>setModal(true)}><UserPlus size={15}/>创建用户</button></header><div className="data-table-wrap"><table className="data-table"><thead><tr><th>用户</th><th>角色</th><th>状态</th><th>失败次数</th><th>最近登录</th><th>操作</th></tr></thead><tbody>{users.map(user=><tr key={user.user_id}><td><b>{user.display_name}</b><small className="block-small">{user.username} · {user.auth_source==='ldap'?'LDAP/AD':'本地'}</small></td><td><select value={user.role} onChange={event=>updateUser(user,{role:event.target.value})}>{Object.entries(roleLabel).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></td><td><button className={user.status==='active'?'result-ok':'result-fail'} onClick={()=>updateUser(user,{status:user.status==='active'?'disabled':'active'})}>{user.status}</button></td><td>{user.failed_attempts}{user.locked_until&&<small className="block-small">锁定至 {new Date(user.locked_until).toLocaleTimeString('zh-CN')}</small>}</td><td>{user.last_login?new Date(user.last_login).toLocaleString('zh-CN'):'从未登录'}</td><td>{user.auth_source==='local'&&<button className="row-action" onClick={()=>resetPassword(user)}>重置密码</button>}{user.mfa_enabled&&<button className="row-action" onClick={()=>resetMfa(user)}>重置 MFA</button>}</td></tr>)}</tbody></table></div></section>}
 {tab==='models'&&<LlmSettingsPanel/>}
 {tab==='security'&&<MfaPanel/>}
 {modal&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setModal(false)}/><form className="modal-card passenger-form" onSubmit={createUser}><header><div><span className="panel__eyebrow">NEW USER</span><h2>创建授权用户</h2></div><button type="button" className="icon-button" onClick={()=>setModal(false)}><X size={19}/></button></header><div className="form-grid"><label><span>用户名</span><input required minLength={3} value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label><span>显示名称</span><input required value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/></label><label><span>初始密码</span><input required type="password" minLength={10} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label><span>角色</span><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{Object.entries(roleLabel).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><footer><button type="button" className="secondary-button" onClick={()=>setModal(false)}>取消</button><button className="primary-button" disabled={busy}><UserPlus size={15}/>创建用户</button></footer></form></div>}
 {toast&&<div className="toast success"><CheckCircle2 size={16}/>{toast}</div>}</div>
}
