import { FormEvent, useEffect, useState } from 'react'
import { Bot, CheckCircle2, CloudDownload, Plus, Save, TestTube2, Trash2, X } from 'lucide-react'
import { postJson, requestJson } from '../api'

type ProviderType='openai'|'openai_compatible'|'anthropic'|'gemini'|'ollama'
interface Provider {
  provider_id:string;name:string;provider_type:ProviderType;base_url:string;has_api_key:boolean
  selected_model:string|null;available_models:string[];enabled:boolean;is_default:boolean
  last_test_status:string|null;last_test_message:string|null;last_tested_at:string|null
}

const providerLabels:Record<ProviderType,string>={openai:'OpenAI',openai_compatible:'OpenAI 兼容（DeepSeek / 百炼 / 智谱等）',anthropic:'Anthropic',gemini:'Google Gemini',ollama:'Ollama / 本地模型'}
const providerUrls:Record<ProviderType,string>={openai:'https://api.openai.com/v1',openai_compatible:'https://api.deepseek.com',anthropic:'https://api.anthropic.com/v1',gemini:'https://generativelanguage.googleapis.com/v1beta',ollama:'http://127.0.0.1:11434'}
const emptyForm={name:'',provider_type:'openai_compatible' as ProviderType,base_url:providerUrls.openai_compatible,api_key:'',selected_model:'',enabled:true,is_default:false}

export default function LlmSettingsPanel(){
  const[providers,setProviders]=useState<Provider[]>([])
  const[keys,setKeys]=useState<Record<string,string>>({})
  const[busy,setBusy]=useState('')
  const[modal,setModal]=useState(false)
  const[form,setForm]=useState(emptyForm)
  const[toast,setToast]=useState('')
  const notify=(message:string)=>{setToast(message);setTimeout(()=>setToast(''),3200)}
  const load=async()=>{try{setProviders(await requestJson('/admin/llm/providers'))}catch(error){notify(error instanceof Error?error.message:'模型供应商加载失败')}}
  useEffect(()=>{load()},[])
  const create=async(event:FormEvent)=>{event.preventDefault();setBusy('create');try{const item=await postJson<Provider>('/admin/llm/providers',form);setProviders(current=>[...current,item]);setModal(false);setForm(emptyForm);notify('模型供应商已保存，密钥已加密')}catch(error){notify(error instanceof Error?error.message:'供应商创建失败')}finally{setBusy('')}}
  const persist=async(provider:Provider,show=true)=>{const payload:Record<string,unknown>={name:provider.name,provider_type:provider.provider_type,base_url:provider.base_url,selected_model:provider.selected_model,enabled:provider.enabled,is_default:provider.is_default};if(keys[provider.provider_id])payload.api_key=keys[provider.provider_id];const item=await requestJson<Provider>(`/admin/llm/providers/${provider.provider_id}`,{method:'PATCH',body:JSON.stringify(payload)});setProviders(current=>current.map(value=>value.provider_id===item.provider_id?item:{...value,is_default:item.is_default?false:value.is_default}));setKeys(current=>({...current,[provider.provider_id]:''}));if(show)notify(`${item.name} 配置已保存`);return item}
  const save=async(provider:Provider)=>{setBusy(provider.provider_id);try{await persist(provider)}catch(error){notify(error instanceof Error?error.message:'配置保存失败')}finally{setBusy('')}}
  const discover=async(provider:Provider)=>{setBusy(provider.provider_id);try{const saved=await persist(provider,false);const result=await postJson<{models:string[];selected_model:string}>(`/admin/llm/providers/${saved.provider_id}/models`);setProviders(current=>current.map(value=>value.provider_id===saved.provider_id?{...value,available_models:result.models,selected_model:result.selected_model}:value));notify(`已获取 ${result.models.length} 个模型`)}catch(error){notify(error instanceof Error?error.message:'获取模型失败')}finally{setBusy('')}}
  const test=async(provider:Provider)=>{setBusy(provider.provider_id);try{const saved=await persist(provider,false);const result=await postJson<{message:string;latency_ms:number}>(`/admin/llm/providers/${saved.provider_id}/test`);await load();notify(`${result.message}（${result.latency_ms} ms）`)}catch(error){notify(error instanceof Error?error.message:'连接测试失败')}finally{setBusy('')}}
  const remove=async(provider:Provider)=>{if(!window.confirm(`确认删除模型供应商“${provider.name}”？`))return;setBusy(provider.provider_id);try{await requestJson(`/admin/llm/providers/${provider.provider_id}`,{method:'DELETE'});setProviders(current=>current.filter(item=>item.provider_id!==provider.provider_id));notify('模型供应商已删除')}catch(error){notify(error instanceof Error?error.message:'删除失败')}finally{setBusy('')}}
  const patch=(id:string,values:Partial<Provider>)=>setProviders(current=>current.map(item=>item.provider_id===id?{...item,...values}:item))
  return <>
    <section className="panel llm-settings-header"><div><span className="eyebrow">LARGE LANGUAGE MODEL</span><h2>大语言模型供应商</h2><p>本平台独立保存连接与密钥；支持发现模型、选择默认模型和真实对话测试。</p></div><button className="primary-button" onClick={()=>setModal(true)}><Plus size={15}/>新增供应商</button></section>
    <section className="source-card-grid">{providers.map(provider=><article className="panel source-config-card" key={provider.provider_id}><header><span className={provider.last_test_status==='success'?'source-health-ok':'source-health-warn'}>{provider.last_test_status==='success'?<CheckCircle2 size={18}/>:<Bot size={18}/>}</span><div><small>{providerLabels[provider.provider_type]}</small><h2><input value={provider.name} onChange={event=>patch(provider.provider_id,{name:event.target.value})}/></h2></div><span className="source-tag">{provider.enabled?'enabled':'disabled'}</span></header>
      <label><span>供应商类型</span><select value={provider.provider_type} onChange={event=>patch(provider.provider_id,{provider_type:event.target.value as ProviderType})}>{Object.entries(providerLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
      <label><span>服务地址</span><input value={provider.base_url} onChange={event=>patch(provider.provider_id,{base_url:event.target.value})}/></label>
      <label><span>API 密钥</span><input type="password" autoComplete="new-password" value={keys[provider.provider_id]??''} onChange={event=>setKeys(current=>({...current,[provider.provider_id]:event.target.value}))} placeholder={provider.has_api_key?'已加密保存；留空保持不变':'输入 API 密钥'}/></label>
      <label><span>当前模型</span><input list={`models-${provider.provider_id}`} value={provider.selected_model??''} onChange={event=>patch(provider.provider_id,{selected_model:event.target.value})} placeholder="获取列表或手工输入模型名"/><datalist id={`models-${provider.provider_id}`}>{provider.available_models.map(model=><option key={model} value={model}/>)}</datalist></label>
      <div className="checkbox-label"><input type="checkbox" checked={provider.enabled} onChange={event=>patch(provider.provider_id,{enabled:event.target.checked})}/><span><b>启用供应商</b></span><input type="checkbox" checked={provider.is_default} onChange={event=>patch(provider.provider_id,{is_default:event.target.checked})}/><span><b>设为默认</b></span></div>
      <dl><div><dt>已发现模型</dt><dd>{provider.available_models.length}</dd></div><div><dt>最近测试</dt><dd>{provider.last_tested_at?new Date(provider.last_tested_at).toLocaleString('zh-CN'):'尚未测试'}</dd></div></dl>{provider.last_test_message&&<p className="source-error">{provider.last_test_message}</p>}
      <footer><button className="row-action" disabled={!!busy} onClick={()=>remove(provider)} title="删除"><Trash2 size={14}/></button><button className="secondary-button" disabled={!!busy} onClick={()=>discover(provider)}><CloudDownload size={14}/>获取模型</button><button className="secondary-button" disabled={!!busy||!provider.selected_model} onClick={()=>test(provider)}><TestTube2 size={14}/>连接测试</button><button className="primary-button" disabled={!!busy} onClick={()=>save(provider)}><Save size={14}/>{busy===provider.provider_id?'处理中…':'保存'}</button></footer>
    </article>)}</section>
    {!providers.length&&<div className="empty-state"><Bot size={30}/><b>尚未配置大语言模型供应商</b><span>互联网端与内网端需分别配置，密钥不会跨平台传递。</span></div>}
    {modal&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setModal(false)}/><form className="modal-card passenger-form" onSubmit={create}><header><div><span className="panel__eyebrow">NEW LLM PROVIDER</span><h2>新增模型供应商</h2></div><button type="button" className="icon-button" onClick={()=>setModal(false)}><X size={19}/></button></header><div className="form-grid"><label><span>配置名称</span><input required value={form.name} onChange={event=>setForm({...form,name:event.target.value})} placeholder="例如：内网推理集群"/></label><label><span>供应商类型</span><select value={form.provider_type} onChange={event=>{const provider_type=event.target.value as ProviderType;setForm({...form,provider_type,base_url:providerUrls[provider_type]})}}>{Object.entries(providerLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>服务地址</span><input required value={form.base_url} onChange={event=>setForm({...form,base_url:event.target.value})}/></label><label><span>API 密钥</span><input type="password" value={form.api_key} onChange={event=>setForm({...form,api_key:event.target.value})} placeholder={form.provider_type==='ollama'?'本地 Ollama 可留空':'输入密钥'}/></label><label><span>模型名称（可稍后获取）</span><input value={form.selected_model} onChange={event=>setForm({...form,selected_model:event.target.value})}/></label><label className="checkbox-label"><input type="checkbox" checked={form.is_default} onChange={event=>setForm({...form,is_default:event.target.checked})}/><span><b>设为本平台默认模型</b></span></label></div><footer><button type="button" className="secondary-button" onClick={()=>setModal(false)}>取消</button><button className="primary-button" disabled={busy==='create'}><Save size={15}/>保存供应商</button></footer></form></div>}
    {toast&&<div className="toast success"><CheckCircle2 size={16}/>{toast}</div>}
  </>
}
