import { useEffect, useRef, useState } from 'react'
import { ArrowDownToLine, CheckCircle2, CloudDownload, FileUp, Inbox, MessageSquareMore, RefreshCw, ShieldCheck } from 'lucide-react'
import { postJson, requestJson, uploadFile } from '../api'

interface ReceiverStatus { status: string; last_package: string | null; last_received_at: string | null; packages_total: number; signature_failures: number; api_polling_enabled:boolean }

export default function ReceiverPage() {
  const [status, setStatus] = useState<ReceiverStatus | null>(null)
  const [busy, setBusy] = useState(false)
  const [toast, setToast] = useState('')
  const fileRef = useRef<HTMLInputElement>(null)
  const notify=(value:string)=>{setToast(value);setTimeout(()=>setToast(''),2800)}
  const refresh=async()=>{setStatus(await requestJson('/transfer/receiver/status'))}
  useEffect(()=>{refresh().catch(error=>notify(error instanceof Error?error.message:'状态加载失败'))},[])
  const action=async(path:string,label:string)=>{setBusy(true);try{const result=await postJson<{total:number}>(path);await refresh();notify(`${label}完成，处理 ${result.total} 个数据包`)}catch(error){notify(error instanceof Error?error.message:`${label}失败`)}finally{setBusy(false)}}
  const upload=async(file:File)=>{setBusy(true);try{const result=await uploadFile<{status:string;records:number}>('/transfer/receiver/upload',file);await refresh();notify(`数据包${result.status}，导入 ${result.records} 条记录`)}catch(error){notify(error instanceof Error?error.message:'数据包导入失败')}finally{setBusy(false)}}
  return <div className="business-page page-enter"><section className="page-heading compact-heading"><div><span className="eyebrow">INTRANET TRANSFER RECEIVER</span><h1>内网数据接收中心</h1><p>验签、解密、解压、Schema 校验与 Package ID 幂等入库。</p></div><div className="heading-actions"><button className="secondary-button" disabled={busy} onClick={refresh}><RefreshCw size={16}/>刷新</button><button className="primary-button" disabled={busy} onClick={()=>fileRef.current?.click()}><FileUp size={16}/>导入数据包</button><input ref={fileRef} hidden type="file" accept=".gpack" onChange={event=>event.target.files?.[0]&&upload(event.target.files[0])}/></div></section><section className="transfer-kpis"><article><span><Inbox size={20}/></span><div><small>累计接收包</small><strong>{status?.packages_total??0}</strong><em>Package ID 幂等</em></div></article><article><span><ShieldCheck size={20}/></span><div><small>验签失败</small><strong>{status?.signature_failures??0}</strong><em>失败包隔离留痕</em></div></article><article><span><ArrowDownToLine size={20}/></span><div><small>最近数据包</small><strong>{status?.last_package?.slice(0,12)??'—'}</strong><em>{status?.last_received_at?new Date(status.last_received_at).toLocaleString('zh-CN'):'尚未接收'}</em></div></article></section><section className="panel receiver-actions"><header className="panel__header"><div><span className="panel__eyebrow">RECEIVE CHANNELS</span><h2>接收通道</h2></div><span className="receiver-online"><i/>{status?.status==='online'?'在线':'检测中'}</span></header><div className="receiver-channel-grid"><button disabled={busy} onClick={()=>action('/transfer/receiver/scan','目录扫描')}><Inbox size={24}/><span><b>网闸文件目录</b><small>扫描配置目录中的 .gpack 文件</small></span></button><button disabled={busy} onClick={()=>action('/transfer/receiver/consume-queue','消息消费')}><MessageSquareMore size={24}/><span><b>消息队列</b><small>消费 RabbitMQ 持久化队列</small></span></button>{status?.api_polling_enabled&&<button disabled={busy} onClick={()=>action('/transfer/receiver/poll-api','白名单 API 轮询')}><CloudDownload size={24}/><span><b>API 白名单轮询</b><small>仅访问配置的 HTTPS 网关</small></span></button>}<button disabled={busy} onClick={()=>fileRef.current?.click()}><FileUp size={24}/><span><b>人工导入</b><small>应急校验并导入签名数据包</small></span></button></div><div className="security-notice"><CheckCircle2 size={18}/><span><b>{status?.api_polling_enabled?'仅开放受控 HTTPS 白名单网关':'接收端不主动访问互联网'}</b><small>默认仅接受受信网闸目录、内网消息中间件或人工审核文件。</small></span></div></section>{toast&&<div className="toast success"><CheckCircle2 size={16}/>{toast}</div>}</div>
}
