import { useMemo, useState } from 'react'
import { ArrowDownToLine, Box, CheckCircle2, CloudCog, DatabaseZap, FileArchive, Gauge, KeyRound, MessageSquareMore, Play, RefreshCw, RotateCcw, Server, ShieldCheck, Timer, X } from 'lucide-react'
import type { TransferTask } from '../types'
import { formatBytes, formatTime } from '../utils'
import { postJson, requestJson } from '../api'

const channelMeta = {
  file: { label:'文件摆渡', icon:FileArchive, desc:'网闸 / 光闸目录扫描' },
  message_queue: { label:'消息队列', icon:MessageSquareMore, desc:'Kafka 单向消费通道' },
  api_polling: { label:'API 轮询', icon:CloudCog, desc:'白名单网关轮询' },
}

export default function TransferPage({ tasks: initial, connected }: { tasks: TransferTask[]; connected: boolean }) {
  const [tasks,setTasks]=useState(initial)
  const [modal,setModal]=useState(false)
  const [channel,setChannel]=useState<TransferTask['channel']>('file')
  const [dataType,setDataType]=useState<TransferTask['data_type']>('incremental')
  const [toast,setToast]=useState('')
  const [busy,setBusy]=useState(false)
  const [filter,setFilter]=useState<'all'|'active'|'failed'>('all')
  const notify=(message:string)=>{setToast(message);setTimeout(()=>setToast(''),2600)}
  const createTask=async()=>{setBusy(true);try{if(!connected)throw new Error('摆渡服务未连接');const task=await postJson<TransferTask>('/transfer/tasks',{channel,data_type:dataType});setTasks(c=>[task,...c]);setModal(false);notify('摆渡任务已创建并完成安全打包')}catch(error){notify(error instanceof Error?error.message:'摆渡任务创建失败')}finally{setBusy(false)}}
  const retry=async(id:string)=>{setBusy(true);try{if(!connected)throw new Error('摆渡服务未连接');const task=await postJson<TransferTask>(`/transfer/tasks/${id}/retry`);setTasks(c=>c.map(item=>item.task_id===id?task:item));notify('失败任务已重新执行')}catch(error){notify(error instanceof Error?error.message:'任务重试失败')}finally{setBusy(false)}}
  const refresh=async()=>{if(!connected){notify('摆渡服务未连接');return}setBusy(true);try{setTasks(await requestJson<TransferTask[]>('/transfer/tasks'));notify('摆渡状态已刷新')}catch(error){notify(error instanceof Error?error.message:'刷新失败')}finally{setBusy(false)}}
  const metrics=useMemo(()=>{const start=new Date();start.setHours(0,0,0,0);const today=tasks.filter(task=>new Date(task.created_at)>=start);const completed=today.filter(task=>task.status==='completed');const failed=today.filter(task=>task.status==='failed');const settled=completed.length+failed.length;const durations=completed.filter(task=>task.completed_at).map(task=>(new Date(task.completed_at!).getTime()-new Date(task.created_at).getTime())/1000);return{today:today.length,completed:completed.length,failed:failed.length,records:completed.reduce((sum,task)=>sum+task.records,0),success:settled?completed.length/settled*100:100,delay:durations.length?durations.reduce((sum,value)=>sum+value,0)/durations.length:0,pending:tasks.filter(task=>task.status==='pending'||task.status==='transferring').length,last:completed[0]?.completed_at}},[tasks])
  const visibleTasks=tasks.filter(task=>filter==='all'||(filter==='failed'?task.status==='failed':task.status==='pending'||task.status==='transferring'))
  return <div className="business-page page-enter">
    <section className="page-heading compact-heading"><div><span className="eyebrow">ONE-WAY DATA TRANSFER</span><h1>数据摆渡中心</h1><p>互联网端向内网端单向加密传输，全链路验签、幂等与审计。</p></div><div className="heading-actions"><button className="secondary-button" disabled={busy} onClick={refresh}><RefreshCw size={16}/>刷新状态</button><button className="primary-button" disabled={busy} onClick={()=>setModal(true)}><Play size={16}/>新建摆渡任务</button></div></section>
    <section className="transfer-topology panel"><div className="topology-node internet"><span><CloudCog size={24}/></span><div><small>INTERNET ZONE</small><b>互联网监测端</b><em><i/>发送服务可用</em></div></div><div className="topology-flow"><span/><div><ShieldCheck size={17}/><b>加密 · 签名 · 完整性校验</b><small>单向传输</small></div><span/></div><div className="topology-gate"><KeyRound size={22}/><span>安全隔离网闸</span><small>由部署策略控制</small></div><div className="topology-flow"><span/><div><ArrowDownToLine size={17}/><b>验签 · 解密 · 幂等</b><small>内网自动入库</small></div><span/></div><div className="topology-node intranet"><span><Server size={24}/></span><div><small>INTRANET ZONE</small><b>内网研判端</b><em>互联网端不反向探测</em></div></div></section>
    <section className="transfer-kpis"><article><span><DatabaseZap size={20}/></span><div><small>今日摆渡任务</small><strong>{metrics.today}</strong><em>成功 {metrics.completed} · 失败 {metrics.failed}</em></div></article><article><span><Box size={20}/></span><div><small>今日打包记录</small><strong>{metrics.records.toLocaleString()}</strong><em>以已完成任务为准</em></div></article><article><span><Gauge size={20}/></span><div><small>传输成功率</small><strong>{metrics.success.toFixed(1)}%</strong><em>今日已结束任务</em></div></article><article><span><Timer size={20}/></span><div><small>平均任务耗时</small><strong>{metrics.delay<60?`${metrics.delay.toFixed(1)}s`:`${(metrics.delay/60).toFixed(1)}m`}</strong><em>创建至打包完成</em></div></article></section>
    <section className="transfer-layout">
      <article className="panel transfer-task-panel"><header className="panel__header"><div><span className="panel__eyebrow">TRANSFER TASKS</span><h2>摆渡任务</h2></div><div className="filter-tabs compact"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>全部</button><button className={filter==='active'?'active':''} onClick={()=>setFilter('active')}>进行中</button><button className={filter==='failed'?'active':''} onClick={()=>setFilter('failed')}>失败</button></div></header><div className="transfer-list"><div className="transfer-list__head"><span>任务 / 数据包</span><span>通道</span><span>数据类型</span><span>记录 / 大小</span><span>状态进度</span><span>创建时间</span><span/></div>{visibleTasks.map(task=>{const meta=channelMeta[task.channel];const Icon=meta.icon;return <div className="transfer-row" key={task.task_id}><span className="task-id"><span className={`task-icon task-icon--${task.status}`}><Icon size={17}/></span><span><b>{task.task_id}</b><small>{task.package_id}</small></span></span><span><b>{meta.label}</b><small>{meta.desc}</small></span><span><span className="source-tag">{task.data_type==='full'?'全量':'增量'}</span></span><span><b>{task.records.toLocaleString()} 条</b><small>{task.size?formatBytes(task.size):'待打包'}</small></span><span className="task-progress"><span className={`task-status task-status--${task.status}`}>{task.status==='completed'?'已完成':task.status==='transferring'?'传输中':task.status==='failed'?'失败':'排队中'}</span><div><i style={{width:`${task.progress}%`}}/></div><small>{task.progress}%</small></span><span>{formatTime(task.created_at)}</span><span>{task.status==='failed'?<button className="row-action" onClick={()=>retry(task.task_id)}><RotateCcw size={14}/>重试</button>:null}</span></div>})}</div></article>
      <aside className="transfer-side"><article className="panel receiver-card"><header className="panel__header"><div><span className="panel__eyebrow">SENDER</span><h2>互联网发送状态</h2></div><span className="receiver-online"><i/>可用</span></header><div className="receiver-ring"><div><strong>{metrics.pending}</strong><span>待完成任务</span></div></div><dl><div><dt>最近完成</dt><dd>{metrics.last?formatTime(metrics.last):'暂无'}</dd></div><div><dt>已记录任务</dt><dd>{tasks.length}</dd></div><div><dt>今日失败</dt><dd className={metrics.failed?'result-fail':'text-teal'}>{metrics.failed}</dd></div><div><dt>内网状态</dt><dd>隔离不可探测</dd></div></dl></article><article className="panel security-chain"><header className="panel__header"><div><span className="panel__eyebrow">SECURITY CHAIN</span><h2>安全处理链</h2></div></header>{['检测完整性 SHA-256','验证配置的数字签名','解密配置的对称算法','Gzip 解压与 Schema 校验','Package ID 幂等入库'].map((item,i)=><div key={item}><span><CheckCircle2 size={14}/></span><b>{item}</b><small>{i===4?'保留版本':'任务执行时强制'}</small></div>)}</article></aside>
    </section>
    {modal&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setModal(false)}/><div className="modal-card transfer-modal"><header><div><span className="panel__eyebrow">NEW TRANSFER</span><h2>新建摆渡任务</h2></div><button className="icon-button" onClick={()=>setModal(false)}><X size={19}/></button></header><div className="transfer-modal__body"><label className="field-label">选择摆渡通道</label><div className="channel-options">{(Object.entries(channelMeta) as [TransferTask['channel'],typeof channelMeta.file][]).map(([key,meta])=>{const Icon=meta.icon;return <button className={channel===key?'active':''} key={key} onClick={()=>setChannel(key)}><Icon size={21}/><span><b>{meta.label}</b><small>{meta.desc}</small></span>{channel===key&&<CheckCircle2 size={16}/>}</button>})}</div><label className="field-label">数据范围</label><div className="data-type-options"><button className={dataType==='incremental'?'active':''} onClick={()=>setDataType('incremental')}><b>增量摆渡</b><small>仅打包上次成功任务后的数据变化</small></button><button className={dataType==='full'?'active':''} onClick={()=>setDataType('full')}><b>全量摆渡</b><small>按数据库当前有效记录实时打包</small></button></div><div className="security-notice"><ShieldCheck size={18}/><span><b>安全策略将自动应用</b><small>Gzip 压缩 → 配置化加密 → 数字签名 → SHA-256 完整性校验</small></span></div></div><footer><button className="secondary-button" disabled={busy} onClick={()=>setModal(false)}>取消</button><button className="primary-button" disabled={busy} onClick={createTask}><Play size={16}/>{busy?'正在创建…':'创建并执行'}</button></footer></div></div>}
    {toast&&<div className="toast success"><CheckCircle2 size={16}/>{toast}</div>}
  </div>
}
