"""initial isolated platform schema

Revision ID: 2f91f43f118c
Revises:
Create Date: 2026-08-18 17:34:27.389267
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2f91f43f118c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.String(length=64), nullable=False),
    sa.Column('log_type', sa.String(length=40), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('actor_role', sa.String(length=40), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('resource', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_log_type'), 'audit_logs', ['log_type'], unique=False)
    op.create_table('backup_records',
    sa.Column('backup_id', sa.String(length=64), nullable=False),
    sa.Column('backup_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('path', sa.String(length=1200), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retention_until', sa.Date(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('backup_id')
    )
    op.create_table('countries',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('health_capacity', sa.Float(), nullable=False),
    sa.Column('travel_intensity', sa.Float(), nullable=False),
    sa.Column('transit_risk', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('passengers',
    sa.Column('passenger_id', sa.String(length=80), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('document_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('name_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('contact_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=False),
    sa.Column('travel_history', sa.JSON(), nullable=False),
    sa.Column('transit_countries', sa.JSON(), nullable=False),
    sa.Column('entry_port', sa.String(length=200), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('flight_no', sa.String(length=30), nullable=True),
    sa.Column('seat_no', sa.String(length=20), nullable=True),
    sa.Column('health_declaration', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('risk_reasons', sa.JSON(), nullable=False),
    sa.Column('advice', sa.JSON(), nullable=False),
    sa.Column('matched_rule_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('passenger_id')
    )
    op.create_index(op.f('ix_passengers_document_hash'), 'passengers', ['document_hash'], unique=False)
    op.create_index(op.f('ix_passengers_risk_level'), 'passengers', ['risk_level'], unique=False)
    op.create_table('raw_records',
    sa.Column('raw_record_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('storage_path', sa.String(length=1200), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('raw_record_id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index(op.f('ix_raw_records_source'), 'raw_records', ['source'], unique=False)
    op.create_table('received_packages',
    sa.Column('package_id', sa.String(length=64), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('package_id')
    )
    op.create_table('rule_definitions',
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('rule_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('action_json', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('rule_id'),
    sa.UniqueConstraint('rule_key', 'version', name='uq_rule_version')
    )
    op.create_index(op.f('ix_rule_definitions_rule_key'), 'rule_definitions', ['rule_key'], unique=False)
    op.create_table('source_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_deduplicated', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_source_runs_source'), 'source_runs', ['source'], unique=False)
    op.create_table('transfer_tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('package_id', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('package_path', sa.String(length=1200), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('package_id')
    )
    op.create_index(op.f('ix_transfer_tasks_status'), 'transfer_tasks', ['status'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=64), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('disease', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('advice', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_country_code'), 'alerts', ['country_code'], unique=False)
    op.create_index(op.f('ix_alerts_level'), 'alerts', ['level'], unique=False)
    op.create_table('country_risk_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_country_risk_history_calculated_at'), 'country_risk_history', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_country_risk_history_country_code'), 'country_risk_history', ['country_code'], unique=False)
    op.create_table('country_risk_scores',
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_index(op.f('ix_country_risk_scores_level'), 'country_risk_scores', ['level'], unique=False)
    op.create_table('disease_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('disease', sa.String(length=160), nullable=False),
    sa.Column('country', sa.String(length=160), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=1200), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('cases', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('transmission', sa.Float(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_record_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.raw_record_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('fingerprint', name='uq_event_fingerprint')
    )
    op.create_index(op.f('ix_disease_events_level'), 'disease_events', ['level'], unique=False)
    op.create_index('ix_event_country_published', 'disease_events', ['country_code', 'published_at'], unique=False)
    op.create_table('rule_execution_log',
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('execution_ms', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rule_definitions.rule_id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_rule_execution_log_rule_id'), 'rule_execution_log', ['rule_id'], unique=False)
    op.create_table('transfer_risks',
    sa.Column('link_id', sa.String(length=64), nullable=False),
    sa.Column('origin_country_code', sa.String(length=3), nullable=False),
    sa.Column('origin', sa.String(length=160), nullable=False),
    sa.Column('destination', sa.String(length=160), nullable=False),
    sa.Column('source_coordinates', sa.JSON(), nullable=False),
    sa.Column('target_coordinates', sa.JSON(), nullable=False),
    sa.Column('via', sa.String(length=160), nullable=False),
    sa.Column('risk', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['origin_country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_index(op.f('ix_transfer_risks_origin_country_code'), 'transfer_risks', ['origin_country_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_risks_origin_country_code'), table_name='transfer_risks')
    op.drop_table('transfer_risks')
    op.drop_index(op.f('ix_rule_execution_log_rule_id'), table_name='rule_execution_log')
    op.drop_table('rule_execution_log')
    op.drop_index('ix_event_country_published', table_name='disease_events')
    op.drop_index(op.f('ix_disease_events_level'), table_name='disease_events')
    op.drop_table('disease_events')
    op.drop_index(op.f('ix_country_risk_scores_level'), table_name='country_risk_scores')
    op.drop_table('country_risk_scores')
    op.drop_index(op.f('ix_country_risk_history_country_code'), table_name='country_risk_history')
    op.drop_index(op.f('ix_country_risk_history_calculated_at'), table_name='country_risk_history')
    op.drop_table('country_risk_history')
    op.drop_index(op.f('ix_alerts_level'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_country_code'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transfer_tasks_status'), table_name='transfer_tasks')
    op.drop_table('transfer_tasks')
    op.drop_index(op.f('ix_source_runs_source'), table_name='source_runs')
    op.drop_table('source_runs')
    op.drop_index(op.f('ix_rule_definitions_rule_key'), table_name='rule_definitions')
    op.drop_table('rule_definitions')
    op.drop_table('received_packages')
    op.drop_index(op.f('ix_raw_records_source'), table_name='raw_records')
    op.drop_table('raw_records')
    op.drop_index(op.f('ix_passengers_risk_level'), table_name='passengers')
    op.drop_index(op.f('ix_passengers_document_hash'), table_name='passengers')
    op.drop_table('passengers')
    op.drop_table('countries')
    op.drop_table('backup_records')
    op.drop_index(op.f('ix_audit_logs_log_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
